/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FORMULARIO.VISTA;

import BASEDATO.EvenConexion;
import BASEDATO.LOCAL.ConnPostgres;
import BUSCAR.ClaVarBuscar;
import CONFIGURACION.Global_datos;
import Evento.JTextField.EvenJTextField;
import Evento.Jframe.EvenJFRAME;
import Evento.Jtable.EvenJtable;
import FORMULARIO.DAO.DAO_caja_cierre;
import FORMULARIO.ENTIDAD.caja_cierre;
import IMPRESORA_POS.PosImprimir_Funcio_Recibo;
import IMPRESORA_POS.PosImprimir_Venta;
import IMPRESORA_POS.PosImprimir_caja_cierre;
import java.sql.Connection;
import javax.swing.JTable;

/**
 *
 * @author Digno
 */
public class FrmCaja_abrir_cerrar extends javax.swing.JInternalFrame {

    private EvenJFRAME evetbl = new EvenJFRAME();
    private EvenJtable eveJtab = new EvenJtable();
    private EvenConexion eveconn = new EvenConexion();
    private EvenJTextField evejtf = new EvenJTextField();
    private ClaVarBuscar vbus = new ClaVarBuscar();
    Connection conn = ConnPostgres.getConnPosgres();
    private String nombre_formulario = "CAJA CIERRE";
    private caja_cierre ENTcc = new caja_cierre();
    private DAO_caja_cierre DAOcc = new DAO_caja_cierre();
    private PosImprimir_caja_cierre poscc = new PosImprimir_caja_cierre();
    private PosImprimir_Venta posven = new PosImprimir_Venta();
    private PosImprimir_Funcio_Recibo posfr=new PosImprimir_Funcio_Recibo();
    private Global_datos gda = new Global_datos();
    private void abrir_formulario() {
        this.setTitle(nombre_formulario);
        evetbl.centrar_formulario_internalframa(this);
        DAOcc.actualizar_tabla_caja_cierre(conn, tblcaja_cierre);
    }
    void seleccionar_caja_detalle() {
        if (!eveJtab.getBoolean_validar_select(tblcaja_cierre)) {
            int fk_idcaja_cierre=eveJtab.getInt_select_id(tblcaja_cierre);
            actualizar_tabla_otros(tblventa, fk_idcaja_cierre,"fk_idventa","in_monto_venta",gda.getTbl_venta());
            actualizar_tabla_otros(tblfuncionario_recibo, fk_idcaja_cierre,"fk_idfuncionario_recibo","eg_monto_recibo_funcionario",gda.getTbl_funcionario());
        }
    }
    void anchotabla_caja_detalle_otros(JTable tabla) {
        int Ancho[] = {5, 15, 60,10, 10};
        eveJtab.setAnchoColumnaJtable(tabla, Ancho);
    }
    private void actualizar_tabla_otros(JTable tabla,int fk_idcaja_cierre,String idtabla,String campomonto,String tabla_origen) {
        String sql = "select cd."+idtabla+" as id,to_char(cd.fecha_creado,'yyyy-MM-dd HH24:MI') as fecha,\n"
                + "cd.descripcion ,cd.estado,TRIM(to_char(cd."+campomonto+",'999G999G999')) as monto \n"
                + "from caja_cierre_item cci,caja_detalle cd  \n"
                + "where cci.fk_idcaja_cierre="+fk_idcaja_cierre
                + " and cci.fk_idcaja_detalle=cd.idcaja_detalle \n"
                + "and cd.tabla_origen='"+tabla_origen+"' \n"
                + " order by 1 desc;";
        eveconn.Select_cargar_jtable(conn, sql, tabla);
        anchotabla_caja_detalle_otros(tabla);
    }
    private void boton_imprimir_caja_cierre(){
        if (!eveJtab.getBoolean_validar_select(tblcaja_cierre)) {
            int idcaja_cierre = eveJtab.getInt_select_id(tblcaja_cierre);
            poscc.boton_imprimir_pos_caja_cierre(conn, idcaja_cierre);
        }
    }
    private void boton_imprimir_venta() {
        if (tblventa.getSelectedRow() >= 0) {
            int idventa_select = eveJtab.getInt_select_id(tblventa);
            posven.boton_imprimir_pos_VENTA(conn, idventa_select);
        }
    }
    private void boton_imprimir_funcionario_recibo() {
        if(tblfuncionario_recibo.getSelectedRow()>=0){
            int idfuncionario_recibo = eveJtab.getInt_select_id(tblfuncionario_recibo);
            posfr.boton_imprimir_pos_funcionario_recibo(conn, idfuncionario_recibo);
        }
    }
    public FrmCaja_abrir_cerrar() {
        initComponents();
        abrir_formulario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblcaja_cierre = new javax.swing.JTable();
        btnimprimir_caja_cierre = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblventa = new javax.swing.JTable();
        btnimprimir_venta1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblfuncionario_recibo = new javax.swing.JTable();
        btnimprimir_recibo = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("TABLA"));

        tblcaja_cierre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblcaja_cierre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblcaja_cierreMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblcaja_cierre);

        btnimprimir_caja_cierre.setText("IMPRIMIR CAJA CIERRE");
        btnimprimir_caja_cierre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimir_caja_cierreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 909, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnimprimir_caja_cierre)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnimprimir_caja_cierre)
                .addGap(0, 51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("PRINCIPAL", jPanel1);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("VENTA"));

        tblventa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblventa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblventaMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tblventa);

        btnimprimir_venta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/venta/ven_imprimir.png"))); // NOI18N
        btnimprimir_venta1.setText("IMPRIMIR VENTA");
        btnimprimir_venta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimir_venta1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 909, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btnimprimir_venta1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnimprimir_venta1))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("VENTA", jPanel3);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("FUNCIONARIO RECIBO"));

        tblfuncionario_recibo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblfuncionario_recibo);

        btnimprimir_recibo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/venta/ven_imprimir.png"))); // NOI18N
        btnimprimir_recibo.setText("IMPRIMIR RECIBO");
        btnimprimir_recibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimir_reciboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 909, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(btnimprimir_recibo)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnimprimir_recibo))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("RECIBO FUNCIONARIO", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        DAOcc.ancho_tabla_caja_cierre(tblcaja_cierre);
    }//GEN-LAST:event_formInternalFrameOpened

    private void tblventaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblventaMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tblventaMouseReleased

    private void tblcaja_cierreMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblcaja_cierreMouseReleased
        // TODO add your handling code here:
        seleccionar_caja_detalle();
    }//GEN-LAST:event_tblcaja_cierreMouseReleased

    private void btnimprimir_caja_cierreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimir_caja_cierreActionPerformed
        // TODO add your handling code here:
        boton_imprimir_caja_cierre();
    }//GEN-LAST:event_btnimprimir_caja_cierreActionPerformed

    private void btnimprimir_reciboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimir_reciboActionPerformed
        // TODO add your handling code here:
        boton_imprimir_funcionario_recibo();
    }//GEN-LAST:event_btnimprimir_reciboActionPerformed

    private void btnimprimir_venta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimir_venta1ActionPerformed
        // TODO add your handling code here:
         boton_imprimir_venta();
    }//GEN-LAST:event_btnimprimir_venta1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnimprimir_caja_cierre;
    private javax.swing.JButton btnimprimir_recibo;
    private javax.swing.JButton btnimprimir_venta1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblcaja_cierre;
    private javax.swing.JTable tblfuncionario_recibo;
    private javax.swing.JTable tblventa;
    // End of variables declaration//GEN-END:variables
}
