/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FORMULARIO.VISTA;

import BASEDATO.LOCAL.ConnPostgres;
import Config_JSON.json_grafico;
import Evento.Fecha.EvenFecha;
import Evento.Grafico.EvenDataSetPelu;
import Evento.Grafico.FunFreeChard;
import Evento.Jframe.EvenJFRAME;
import Evento.Mensaje.EvenMensajeJoptionpane;
import java.sql.Connection;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Digno
 */

public class FrmGraficoTodo extends javax.swing.JInternalFrame {
    private EvenJFRAME evetbl = new EvenJFRAME();
    private EvenDataSetPelu evedata=new EvenDataSetPelu();
    private FunFreeChard chard = new FunFreeChard();
    private EvenMensajeJoptionpane evemen = new EvenMensajeJoptionpane();
    private Connection conn = ConnPostgres.getConnPosgres();
    private EvenFecha evefec = new EvenFecha();
    private json_grafico jsongra=new json_grafico();
    private String nombre_formulario = "GRAFICOS TODO";

    private void abrir_formulario() {
        this.setTitle(nombre_formulario);
        jsongra.cargar_jsom_grafico();
        evetbl.centrar_formulario_internalframa(this);
        evefec.cargar_combobox_intervalo_fecha(cmbfiltro_fecha);
//        panel_producto_vendido_cantidad.
    }
    private void grafico_producto_vendido_cantidad() {
        String filtro = "";
        filtro = filtro + evefec.getIntervalo_fecha_combobox(cmbfiltro_fecha, "v.fecha_creado");
        String top=jsongra.getTop_producto_vendido();
        DefaultCategoryDataset dataset = evedata.createDataset_producto_mas_vendido(conn,"iv.cantidad",filtro,top);
        String titulo = "PRODUCTO CANTIDAD TOP:"+top;
        String plano_horizontal = "PRODUCTOS";
        String plano_vertical = "CANTIDAD";
        chard.crear_graficoBar3D(panel_producto_vendido_cantidad, dataset, titulo, plano_horizontal, plano_vertical);
    }
    private void grafico_producto_vendido_monto() {
        String filtro = "";
        filtro = filtro + evefec.getIntervalo_fecha_combobox(cmbfiltro_fecha, "v.fecha_creado");
        String top=jsongra.getTop_producto_vendido();
        DefaultCategoryDataset dataset = evedata.createDataset_producto_mas_vendido(conn,"iv.cantidad*iv.precio_venta",filtro,top);
        String titulo = "PRODUCTO MONTO TOP:"+top;
        String plano_horizontal = "PRODUCTOS";
        String plano_vertical = "MONTO";
        chard.crear_graficoBar3D(panel_producto_vendido_monto, dataset, titulo, plano_horizontal, plano_vertical);
    }
    public FrmGraficoTodo() {
        initComponents();
        abrir_formulario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        panel_producto_vendido_cantidad = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        cmbfiltro_fecha = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        btnconfig = new javax.swing.JButton();
        panel_producto_vendido_monto = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);

        panel_producto_vendido_cantidad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout panel_producto_vendido_cantidadLayout = new javax.swing.GroupLayout(panel_producto_vendido_cantidad);
        panel_producto_vendido_cantidad.setLayout(panel_producto_vendido_cantidadLayout);
        panel_producto_vendido_cantidadLayout.setHorizontalGroup(
            panel_producto_vendido_cantidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );
        panel_producto_vendido_cantidadLayout.setVerticalGroup(
            panel_producto_vendido_cantidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButton1.setText("VER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cmbfiltro_fecha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbfiltro_fecha.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbfiltro_fechaItemStateChanged(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Fecha:");

        btnconfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ABM/config.png"))); // NOI18N
        btnconfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconfigActionPerformed(evt);
            }
        });

        panel_producto_vendido_monto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout panel_producto_vendido_montoLayout = new javax.swing.GroupLayout(panel_producto_vendido_monto);
        panel_producto_vendido_monto.setLayout(panel_producto_vendido_montoLayout);
        panel_producto_vendido_montoLayout.setHorizontalGroup(
            panel_producto_vendido_montoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 557, Short.MAX_VALUE)
        );
        panel_producto_vendido_montoLayout.setVerticalGroup(
            panel_producto_vendido_montoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_producto_vendido_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbfiltro_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnconfig, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_producto_vendido_monto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel18)
                    .addComponent(cmbfiltro_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(btnconfig, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_producto_vendido_monto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_producto_vendido_cantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("VENTA PRODUCTO", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        grafico_producto_vendido_cantidad();
        grafico_producto_vendido_monto();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbfiltro_fechaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbfiltro_fechaItemStateChanged
        // TODO add your handling code here:
//        boton_imprimir(false);
    }//GEN-LAST:event_cmbfiltro_fechaItemStateChanged

    private void btnconfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconfigActionPerformed
        // TODO add your handling code here:
        jsongra.abrir_config_grafico();
    }//GEN-LAST:event_btnconfigActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnconfig;
    private javax.swing.JComboBox<String> cmbfiltro_fecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panel_producto_vendido_cantidad;
    private javax.swing.JPanel panel_producto_vendido_monto;
    // End of variables declaration//GEN-END:variables
}
