/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FORMULARIO.VISTA;

import BASEDATO.EvenConexion;
import BASEDATO.LOCAL.ConnPostgres;
import BASEDATO.LOCAL.VariablesBD;
import Config_JSON.json_array;
//import Config_JSON.json_config;
import Config_JSON.json_imprimir_pos;
import Config_JSON.json_sql_actualizar;
import Evento.Color.cla_color_palete;
import Evento.Fecha.EvenFecha;
import Evento.Jframe.EvenJFRAME;
import Evento.Mensaje.EvenMensajeJoptionpane;
import FORMULARIO.DAO.DAO_caja_cierre;
import FORMULARIO.DAO.DAO_empresa;
import FORMULARIO.ENTIDAD.empresa;
import FORMULARIO.ENTIDAD.usuario;
//import REPORTE.PRODUCTO.cla_InvPro_compra_todos;
import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author Digno
 */
public class FrmMenuPelu extends javax.swing.JFrame {

    private Connection conn = null;
    private ConnPostgres conPs = new ConnPostgres();
    private VariablesBD var = new VariablesBD();
    private json_sql_actualizar json_sql = new json_sql_actualizar();
    private EvenJFRAME evetbl = new EvenJFRAME();
    private EvenFecha evefec = new EvenFecha();
    private EvenMensajeJoptionpane evemen = new EvenMensajeJoptionpane();
    private usuario ENTusu = new usuario();
    private cla_color_palete clacolor = new cla_color_palete();
    private EvenConexion eveconn = new EvenConexion();
    private DAO_caja_cierre DAOcc = new DAO_caja_cierre();
    private empresa ENTemp = new empresa();
    private DAO_empresa DAOemp = new DAO_empresa();
    private json_imprimir_pos jsprint = new json_imprimir_pos();
    private json_array jsarr = new json_array();
    private String version_estatica = "V:1.1";

    void abrir_formulario() {
        jsprint.cargar_jsom_imprimir_pos();
        json_sql.cargar_jsom_sql_actualizar();
        conPs.ConnectDBpostgres(false);
        conn = conPs.getConnPosgres();
        ENTusu.setGlobal_nombre("DIGNO");
        this.setExtendedState(MAXIMIZED_BOTH);
        titulo_sistema();
        cargar_colores();
        actualizacion_version_v1();
        DAOemp.cargar_empresa(conn, ENTemp, 1);
        lblversion.setText(version_estatica);
    }

    void cargar_colores() {
        clacolor.setCol_btn_exit(new Color(93, 84, 164));
        clacolor.setCol_btn_move(new Color(42, 61, 102));
        clacolor.setCol_btn_move_error(new Color(93, 84, 164));
        clacolor.setCol_btn_move_ok(Color.magenta);
        clacolor.setCol_panel_dato(new Color(154, 179, 245));
        clacolor.setCol_panel_tabla(new Color(163, 216, 244));
        clacolor.setColor_referencia(new Color(102, 153, 255));//[102,153,255]
        clacolor.setColor_insertar_primario(new Color(217, 228, 221));
        clacolor.setColor_insertar_secundario(new Color(205, 201, 195));
        clacolor.setColor_importacion(new Color(255, 253, 162));
        clacolor.setColor_exportacion(new Color(163, 218, 141));
        clacolor.setColor_proforma(new Color(168, 159, 158));
    }

    void titulo_sistema() {
        String titulo = " BD: " + var.getPsLocalhost() + "/" + var.getPsPort() + "/" + var.getPsNomBD()
                + "/ Nombre:";
        this.setTitle(titulo);

    }

    void actualizacion_version_v1() {
        /**
         * ALTER TABLE cliente ADD COLUMN delivery boolean; update cliente set
         * delivery=true; update gastos set fk_idusuario=7 where fk_idusuario=1;
         * alter table itemventacomanda alter column preciocompra type
         * numeric(14,0) using preciocompra::numeric;
         */
//        ALTER TABLE liquidacion_final ADD COLUMN fecha_pagado TIMESTAMP  NULL DEFAULT 'now()' ;
//ALTER TABLE liquidacion_final ADD COLUMN monto_pagado NUMERIC(20,0)  NULL DEFAULT 0;
        String sql = "DO $$ \n"
                + "    BEGIN\n"
                + "        BEGIN\n "
                + json_sql.getSql_ahora() + "\n"
                + json_sql.getUlt_sql() + "\n"
                + "        EXCEPTION\n"
                + "            WHEN duplicate_column THEN RAISE NOTICE 'duplicate_column.';\n"
                + "        END;\n"
                + "    END;\n"
                + "$$ ";
        eveconn.SQL_execute_libre(conn, sql);
    }

    public FrmMenuPelu() {
        initComponents();
        abrir_formulario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        btnproducto = new javax.swing.JButton();
        btnservicio = new javax.swing.JButton();
        btnfuncionario = new javax.swing.JButton();
        btncliente = new javax.swing.JButton();
        btnventa = new javax.swing.JButton();
        btncaja_cierre = new javax.swing.JButton();
        btngasto = new javax.swing.JButton();
        btncompra = new javax.swing.JButton();
        btngrafico = new javax.swing.JButton();
        lblversion = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        btncerrarcaja = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_venta = new javax.swing.JMenu();
        jMenuItem_venta = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu_compra = new javax.swing.JMenu();
        jMenuItem_compra = new javax.swing.JMenuItem();
        jMenuItem_proveedor = new javax.swing.JMenuItem();
        jMenu_producto = new javax.swing.JMenu();
        jMenuItem_producto = new javax.swing.JMenuItem();
        jMenuItem_producto_unidad = new javax.swing.JMenuItem();
        jMenuItem_producto_categoria = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu_servicio = new javax.swing.JMenu();
        jMenuItem_servicio = new javax.swing.JMenuItem();
        jMenuItem_servicio_categoria = new javax.swing.JMenuItem();
        jMenuItem_servicio_combo = new javax.swing.JMenuItem();
        jMenu_gasto = new javax.swing.JMenu();
        jMenuItem_gasto = new javax.swing.JMenuItem();
        jMenuItem_gasto_tipo = new javax.swing.JMenuItem();
        jMenu_funcionario = new javax.swing.JMenu();
        jMenuItem_funcionario = new javax.swing.JMenuItem();
        jMenuItem_funcionario_recibo = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu_cliente = new javax.swing.JMenu();
        jMenuItem_cliente = new javax.swing.JMenuItem();
        jMenu_configuracion = new javax.swing.JMenu();
        jMenuItem_usuario = new javax.swing.JMenuItem();
        jMenuItem_config_puntaje = new javax.swing.JMenuItem();
        jMenuItem_empresa = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu_caja = new javax.swing.JMenu();
        jMenuItem_caja_abrir = new javax.swing.JMenuItem();
        jMenuItem_caja_cerrar = new javax.swing.JMenuItem();
        jMenuItem_caja_detalle = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("BOTONES"));

        btnproducto.setText("PRODUCTO");
        btnproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproductoActionPerformed(evt);
            }
        });

        btnservicio.setText("SERVICIO");
        btnservicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnservicioActionPerformed(evt);
            }
        });

        btnfuncionario.setText("FUNCIONARIO");
        btnfuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfuncionarioActionPerformed(evt);
            }
        });

        btncliente.setText("CLIENTE");
        btncliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclienteActionPerformed(evt);
            }
        });

        btnventa.setText("VENTA");
        btnventa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnventaActionPerformed(evt);
            }
        });

        btncaja_cierre.setText("CAJA CIERRE");
        btncaja_cierre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncaja_cierreActionPerformed(evt);
            }
        });

        btngasto.setText("GASTO");
        btngasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngastoActionPerformed(evt);
            }
        });

        btncompra.setText("COMPRA");
        btncompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncompraActionPerformed(evt);
            }
        });

        btngrafico.setText("GRAFICO");
        btngrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngraficoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnventa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnproducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnservicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btngasto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnfuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btncompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btncliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btncaja_cierre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btngrafico)
                .addContainerGap(340, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnproducto)
                    .addComponent(btnservicio)
                    .addComponent(btnfuncionario)
                    .addComponent(btncliente)
                    .addComponent(btncaja_cierre)
                    .addComponent(btngrafico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnventa)
                    .addComponent(btngasto)
                    .addComponent(btncompra))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        lblversion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblversion.setText("jLabel1");

        lblusuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblusuario.setText("user");

        btncerrarcaja.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btncerrarcaja.setText("CERRAR LA CAJA");
        btncerrarcaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarcajaActionPerformed(evt);
            }
        });

        escritorio.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(lblversion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(lblusuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(btncerrarcaja, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblversion, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncerrarcaja, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblversion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btncerrarcaja, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 403, Short.MAX_VALUE))
        );

        jMenu_venta.setText("VENTA");

        jMenuItem_venta.setText("VENTA Y SERVICIO");
        jMenuItem_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ventaActionPerformed(evt);
            }
        });
        jMenu_venta.add(jMenuItem_venta);

        jMenu3.setText("INFORMES");

        jMenuItem6.setText("VENTA FECHA CLIENTE");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenu_venta.add(jMenu3);

        jMenuBar1.add(jMenu_venta);

        jMenu_compra.setText("COMPRA");

        jMenuItem_compra.setText("COMPRA");
        jMenuItem_compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_compraActionPerformed(evt);
            }
        });
        jMenu_compra.add(jMenuItem_compra);

        jMenuItem_proveedor.setText("PROVEEDOR");
        jMenuItem_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_proveedorActionPerformed(evt);
            }
        });
        jMenu_compra.add(jMenuItem_proveedor);

        jMenuBar1.add(jMenu_compra);

        jMenu_producto.setText("PRODUCTO");

        jMenuItem_producto.setText("NUEVO PRODUCTO");
        jMenuItem_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_productoActionPerformed(evt);
            }
        });
        jMenu_producto.add(jMenuItem_producto);

        jMenuItem_producto_unidad.setText("PRODUCTO UNIDAD");
        jMenuItem_producto_unidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_producto_unidadActionPerformed(evt);
            }
        });
        jMenu_producto.add(jMenuItem_producto_unidad);

        jMenuItem_producto_categoria.setText("PRODUCTO CATEGORIA");
        jMenuItem_producto_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_producto_categoriaActionPerformed(evt);
            }
        });
        jMenu_producto.add(jMenuItem_producto_categoria);

        jMenu1.setText("INFORME PRODUCTO");

        jMenuItem3.setText("INVENTARIO VALORIZADO");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenu_producto.add(jMenu1);

        jMenuBar1.add(jMenu_producto);

        jMenu_servicio.setText("SERVICIO");

        jMenuItem_servicio.setText("SERVICIO");
        jMenuItem_servicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_servicioActionPerformed(evt);
            }
        });
        jMenu_servicio.add(jMenuItem_servicio);

        jMenuItem_servicio_categoria.setText("SERVICIO CATEGORIA");
        jMenuItem_servicio_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_servicio_categoriaActionPerformed(evt);
            }
        });
        jMenu_servicio.add(jMenuItem_servicio_categoria);

        jMenuItem_servicio_combo.setText("COMBO SERVICIO");
        jMenu_servicio.add(jMenuItem_servicio_combo);

        jMenuBar1.add(jMenu_servicio);

        jMenu_gasto.setText("GASTO");

        jMenuItem_gasto.setText("DATO GASTO");
        jMenuItem_gasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_gastoActionPerformed(evt);
            }
        });
        jMenu_gasto.add(jMenuItem_gasto);

        jMenuItem_gasto_tipo.setText("GASTO TIPO");
        jMenuItem_gasto_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_gasto_tipoActionPerformed(evt);
            }
        });
        jMenu_gasto.add(jMenuItem_gasto_tipo);

        jMenuBar1.add(jMenu_gasto);

        jMenu_funcionario.setText("FUNCIONARIO");

        jMenuItem_funcionario.setText("FUNCIONARIO");
        jMenuItem_funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_funcionarioActionPerformed(evt);
            }
        });
        jMenu_funcionario.add(jMenuItem_funcionario);

        jMenuItem_funcionario_recibo.setText("RECIBO FUNCIONARIO");
        jMenu_funcionario.add(jMenuItem_funcionario_recibo);

        jMenu2.setText("INFORME FUNCIONARIO");

        jMenuItem4.setText("FILTRO COMISION ");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("PAGO DE COMISION");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenu_funcionario.add(jMenu2);

        jMenuBar1.add(jMenu_funcionario);

        jMenu_cliente.setText("CLIENTE");

        jMenuItem_cliente.setText("CLIENTE");
        jMenuItem_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_clienteActionPerformed(evt);
            }
        });
        jMenu_cliente.add(jMenuItem_cliente);

        jMenuBar1.add(jMenu_cliente);

        jMenu_configuracion.setText("CONFIGURACION");

        jMenuItem_usuario.setText("USUARIO");
        jMenuItem_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_usuarioActionPerformed(evt);
            }
        });
        jMenu_configuracion.add(jMenuItem_usuario);

        jMenuItem_config_puntaje.setText("CONFIGURACION PUNTAJE");
        jMenuItem_config_puntaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_config_puntajeActionPerformed(evt);
            }
        });
        jMenu_configuracion.add(jMenuItem_config_puntaje);

        jMenuItem_empresa.setText("EMPRESA");
        jMenuItem_empresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_empresaActionPerformed(evt);
            }
        });
        jMenu_configuracion.add(jMenuItem_empresa);

        jMenuItem1.setText("CONFIGURAR JSON FORMULARIO");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu_configuracion.add(jMenuItem1);

        jMenuBar1.add(jMenu_configuracion);

        jMenu_caja.setText("CAJA");

        jMenuItem_caja_abrir.setText("ABRIR CAJA");
        jMenuItem_caja_abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_caja_abrirActionPerformed(evt);
            }
        });
        jMenu_caja.add(jMenuItem_caja_abrir);

        jMenuItem_caja_cerrar.setText("CERRAR CAJA");
        jMenuItem_caja_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_caja_cerrarActionPerformed(evt);
            }
        });
        jMenu_caja.add(jMenuItem_caja_cerrar);

        jMenuItem_caja_detalle.setText("CAJA DETALLE");
        jMenu_caja.add(jMenuItem_caja_detalle);

        jMenuItem2.setText("CAJA ABRIR CERRAR");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu_caja.add(jMenuItem2);

        jMenuBar1.add(jMenu_caja);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        JDiaLogin log = new JDiaLogin(this, true);
        log.setVisible(true);
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem_gasto_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_gasto_tipoActionPerformed
        // TODO add your handling code here:
        evetbl.abrir_TablaJinternal(new FrmGasto_tipo());
    }//GEN-LAST:event_jMenuItem_gasto_tipoActionPerformed

    private void jMenuItem_gastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_gastoActionPerformed
        // TODO add your handling code here:
        evetbl.abrir_TablaJinternal(new FrmGasto());
    }//GEN-LAST:event_jMenuItem_gastoActionPerformed

    private void jMenuItem_producto_unidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_producto_unidadActionPerformed
        // TODO add your handling code here:
        evetbl.abrir_TablaJinternal(new FrmProducto_unidad());
    }//GEN-LAST:event_jMenuItem_producto_unidadActionPerformed

    private void jMenuItem_producto_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_producto_categoriaActionPerformed
        // TODO add your handling code here:
        evetbl.abrir_TablaJinternal(new FrmProducto_categoria());
    }//GEN-LAST:event_jMenuItem_producto_categoriaActionPerformed

    private void jMenuItem_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_productoActionPerformed
        // TODO add your handling code here:
        evetbl.abrir_TablaJinternal(new FrmProducto());
    }//GEN-LAST:event_jMenuItem_productoActionPerformed

    private void btnproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproductoActionPerformed
        // TODO add your handling code here:
        evetbl.abrir_TablaJinternal(new FrmProducto());
    }//GEN-LAST:event_btnproductoActionPerformed

    private void jMenuItem_servicio_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_servicio_categoriaActionPerformed
        // TODO add your handling code here:
        evetbl.abrir_TablaJinternal(new FrmServicio_categoria());
    }//GEN-LAST:event_jMenuItem_servicio_categoriaActionPerformed

    private void jMenuItem_servicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_servicioActionPerformed
        // TODO add your handling code here:
        evetbl.abrir_TablaJinternal(new FrmServicio());
    }//GEN-LAST:event_jMenuItem_servicioActionPerformed

    private void btnservicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnservicioActionPerformed
        // TODO add your handling code here:
        evetbl.abrir_TablaJinternal(new FrmServicio());
    }//GEN-LAST:event_btnservicioActionPerformed

    private void jMenuItem_funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_funcionarioActionPerformed
        // TODO add your handling code here:
        evetbl.abrir_TablaJinternal(new FrmFuncionario());
    }//GEN-LAST:event_jMenuItem_funcionarioActionPerformed

    private void btnfuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfuncionarioActionPerformed
        // TODO add your handling code here:
        evetbl.abrir_TablaJinternal(new FrmFuncionario());
    }//GEN-LAST:event_btnfuncionarioActionPerformed

    private void jMenuItem_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_clienteActionPerformed
        // TODO add your handling code here:
        evetbl.abrir_TablaJinternal(new FrmCliente());
    }//GEN-LAST:event_jMenuItem_clienteActionPerformed

    private void btnclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclienteActionPerformed
        // TODO add your handling code here:
        evetbl.abrir_TablaJinternal(new FrmCliente());
    }//GEN-LAST:event_btnclienteActionPerformed

    private void jMenuItem_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_proveedorActionPerformed
        // TODO add your handling code here:
        evetbl.abrir_TablaJinternal(new FrmProveedor());
    }//GEN-LAST:event_jMenuItem_proveedorActionPerformed

    private void jMenuItem_config_puntajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_config_puntajeActionPerformed
        // TODO add your handling code here:
        evetbl.abrir_TablaJinternal(new FrmConfiguracion_puntaje());
    }//GEN-LAST:event_jMenuItem_config_puntajeActionPerformed

    private void btnventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnventaActionPerformed
        // TODO add your handling code here:
        evetbl.abrir_TablaJinternal(new FrmVenta());
    }//GEN-LAST:event_btnventaActionPerformed

    private void jMenuItem_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ventaActionPerformed
        // TODO add your handling code here:
        evetbl.abrir_TablaJinternal(new FrmVenta());
    }//GEN-LAST:event_jMenuItem_ventaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        jsarr.abrir_config_formulario();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem_caja_abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_caja_abrirActionPerformed
        // TODO add your handling code here:
        if (DAOcc.getboo_existe_abierto_cargar_caja_cierre(conn)) {
            JDiaAbrir_Caja frm = new JDiaAbrir_Caja(null, true);
            frm.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "YA EXISTE UNA CAJA ABIERTO PRIMERO SE DEBE CERRAR");
        }

    }//GEN-LAST:event_jMenuItem_caja_abrirActionPerformed

    private void jMenuItem_caja_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_caja_cerrarActionPerformed
        // TODO add your handling code here:
        if (!DAOcc.getboo_existe_abierto_cargar_caja_cierre(conn)) {
            evetbl.abrir_TablaJinternal(new FrmCaja_Cierre());
        } else {
            JOptionPane.showMessageDialog(null, "NO EXISTE UNA CAJA ABIERTO PRIMERO SE DEBE ABRIR");
        }
    }//GEN-LAST:event_jMenuItem_caja_cerrarActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        evetbl.abrir_TablaJinternal(new FrmCaja_abrir_cerrar());
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btncaja_cierreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncaja_cierreActionPerformed
        // TODO add your handling code here:
        evetbl.abrir_TablaJinternal(new FrmCaja_abrir_cerrar());
    }//GEN-LAST:event_btncaja_cierreActionPerformed

    private void jMenuItem_empresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_empresaActionPerformed
        // TODO add your handling code here:
        evetbl.abrir_TablaJinternal(new FrmEmpresa());
    }//GEN-LAST:event_jMenuItem_empresaActionPerformed

    private void jMenuItem_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_usuarioActionPerformed
        // TODO add your handling code here:
        evetbl.abrir_TablaJinternal(new FrmUsuario());
    }//GEN-LAST:event_jMenuItem_usuarioActionPerformed

    private void btngastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngastoActionPerformed
        // TODO add your handling code here:
        evetbl.abrir_TablaJinternal(new FrmGasto());
    }//GEN-LAST:event_btngastoActionPerformed

    private void btncompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncompraActionPerformed
        // TODO add your handling code here:
        evetbl.abrir_TablaJinternal(new FrmCompra());
    }//GEN-LAST:event_btncompraActionPerformed

    private void jMenuItem_compraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_compraActionPerformed
        // TODO add your handling code here:
        evetbl.abrir_TablaJinternal(new FrmCompra());
    }//GEN-LAST:event_jMenuItem_compraActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        evetbl.abrir_TablaJinternal(new FrmRepInventarioVenta());
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        evetbl.abrir_TablaJinternal(new FrmRepFuncioComision());
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        evetbl.abrir_TablaJinternal(new FrmRepFuncioComisionPago());
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        evetbl.abrir_TablaJinternal(new FrmRepVentaFecCli());
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void btncerrarcajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarcajaActionPerformed
        // TODO add your handling code here:
        if (!DAOcc.getboo_existe_abierto_cargar_caja_cierre(conn)) {
            evetbl.abrir_TablaJinternal(new FrmCaja_Cierre());
        } else {
            JOptionPane.showMessageDialog(null, "NO EXISTE UNA CAJA ABIERTO PRIMERO SE DEBE ABRIR");
        }
    }//GEN-LAST:event_btncerrarcajaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if (!DAOcc.getboo_existe_abierto_cargar_caja_cierre(conn)) {
            if (evemen.MensajeGeneral_question("LA CAJA NO SE CERRO", "CERRAR SISTEMA", "CERRAR CAJA", "CERRAR SISTEMA")) {
                evetbl.abrir_TablaJinternal(new FrmCaja_Cierre());
            }else{
                System.exit(0);
            }
        }
    }//GEN-LAST:event_formWindowClosing

    private void btngraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngraficoActionPerformed
        // TODO add your handling code here:
        evetbl.abrir_TablaJinternal(new FrmGraficoTodo());
    }//GEN-LAST:event_btngraficoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPelu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPelu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPelu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPelu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuPelu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncaja_cierre;
    private javax.swing.JButton btncerrarcaja;
    private javax.swing.JButton btncliente;
    private javax.swing.JButton btncompra;
    private javax.swing.JButton btnfuncionario;
    private javax.swing.JButton btngasto;
    private javax.swing.JButton btngrafico;
    private javax.swing.JButton btnproducto;
    private javax.swing.JButton btnservicio;
    private javax.swing.JButton btnventa;
    public static javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem_caja_abrir;
    private javax.swing.JMenuItem jMenuItem_caja_cerrar;
    private javax.swing.JMenuItem jMenuItem_caja_detalle;
    private javax.swing.JMenuItem jMenuItem_cliente;
    private javax.swing.JMenuItem jMenuItem_compra;
    private javax.swing.JMenuItem jMenuItem_config_puntaje;
    private javax.swing.JMenuItem jMenuItem_empresa;
    private javax.swing.JMenuItem jMenuItem_funcionario;
    private javax.swing.JMenuItem jMenuItem_funcionario_recibo;
    private javax.swing.JMenuItem jMenuItem_gasto;
    private javax.swing.JMenuItem jMenuItem_gasto_tipo;
    private javax.swing.JMenuItem jMenuItem_producto;
    private javax.swing.JMenuItem jMenuItem_producto_categoria;
    private javax.swing.JMenuItem jMenuItem_producto_unidad;
    private javax.swing.JMenuItem jMenuItem_proveedor;
    private javax.swing.JMenuItem jMenuItem_servicio;
    private javax.swing.JMenuItem jMenuItem_servicio_categoria;
    private javax.swing.JMenuItem jMenuItem_servicio_combo;
    private javax.swing.JMenuItem jMenuItem_usuario;
    private javax.swing.JMenuItem jMenuItem_venta;
    public static javax.swing.JMenu jMenu_caja;
    public static javax.swing.JMenu jMenu_cliente;
    public static javax.swing.JMenu jMenu_compra;
    public static javax.swing.JMenu jMenu_configuracion;
    public static javax.swing.JMenu jMenu_funcionario;
    public static javax.swing.JMenu jMenu_gasto;
    public static javax.swing.JMenu jMenu_producto;
    public static javax.swing.JMenu jMenu_servicio;
    public static javax.swing.JMenu jMenu_venta;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel lblusuario;
    private javax.swing.JLabel lblversion;
    // End of variables declaration//GEN-END:variables
}
