/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FORMULARIO.VISTA;

import BASEDATO.EvenConexion;
import BASEDATO.LOCAL.ConnPostgres;
import CONFIGURACION.Global_datos;
import Evento.Fecha.EvenFecha;
import Evento.JTextField.EvenJTextField;
import Evento.Jframe.EvenJFRAME;
import Evento.Jtable.EvenJtable;
import Evento.Mensaje.EvenMensajeJoptionpane;
import FORMULARIO.BO.BO_caja_cierre;
import FORMULARIO.DAO.DAO_caja_cierre;
import FORMULARIO.DAO.DAO_caja_detalle;
import FORMULARIO.ENTIDAD.caja_cierre;
import FORMULARIO.ENTIDAD.caja_detalle;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author Digno
 */
public class JDiaAbrir_Caja extends javax.swing.JDialog {

   private EvenJFRAME evetbl = new EvenJFRAME();
    private EvenJtable eveJtab = new EvenJtable();
    private EvenConexion eveconn = new EvenConexion();
    private EvenMensajeJoptionpane evemen = new EvenMensajeJoptionpane();
    private EvenJTextField evejtf = new EvenJTextField();
    private EvenFecha evefec = new EvenFecha();
    private Global_datos gda=new Global_datos();
    private Connection conn = ConnPostgres.getConnPosgres();
    private caja_cierre ENTcc=new caja_cierre();
    private BO_caja_cierre BOcc=new BO_caja_cierre();
    private caja_detalle ENTcd=new caja_detalle();
    private DAO_caja_detalle DAOcd=new DAO_caja_detalle();
    private DAO_caja_cierre DAOcc=new DAO_caja_cierre();
    
    private String nombre_formulario = "ABRIR CAJA";
    private void abrir_formulario(){
        this.setTitle(nombre_formulario);
        
    }
    private void  cargar_dato_caja_cierre(){
        ENTcc.setC3creado_por(gda.getCreado_por());
        ENTcc.setC6estado(gda.getEstado_abierto());
    }
     private void cargar_dato_caja_detalle(){
        DAOcd.vaciar_caja_detalle(ENTcd);
        ENTcd.setC4descripcion(gda.getTbl_caja()+"=>"+nombre_formulario);
        ENTcd.setC5tabla_origen(gda.getTbl_caja());
        ENTcd.setC8cierre(gda.getCaja_abierto());
        ENTcd.setC6estado(gda.getEstado_emitido());
        ENTcd.setC9in_monto_apertura(evejtf.getDouble_format_nro_entero(txtmonto_caja_apertura));
    }
    private void boton_caja_cierre(){
        if(txtmonto_caja_apertura.getText().trim().length()>0){
            cargar_dato_caja_cierre();
            cargar_dato_caja_detalle();
            BOcc.insertar_caja_cierre(ENTcc, ENTcd);
            this.dispose();
        }
    }
    public JDiaAbrir_Caja(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        abrir_formulario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_insert1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtmonto_caja_apertura = new javax.swing.JTextField();
        btncaja_abrir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CAJA ABRIR");

        txtmonto_caja_apertura.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        txtmonto_caja_apertura.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtmonto_caja_apertura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmonto_caja_aperturaActionPerformed(evt);
            }
        });
        txtmonto_caja_apertura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtmonto_caja_aperturaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtmonto_caja_aperturaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmonto_caja_aperturaKeyTyped(evt);
            }
        });

        btncaja_abrir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btncaja_abrir.setText("CAJA ABRIR");
        btncaja_abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncaja_abrirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_insert1Layout = new javax.swing.GroupLayout(panel_insert1);
        panel_insert1.setLayout(panel_insert1Layout);
        panel_insert1Layout.setHorizontalGroup(
            panel_insert1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_insert1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_insert1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btncaja_abrir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtmonto_caja_apertura, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_insert1Layout.setVerticalGroup(
            panel_insert1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_insert1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtmonto_caja_apertura, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btncaja_abrir, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_insert1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_insert1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtmonto_caja_aperturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmonto_caja_aperturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmonto_caja_aperturaActionPerformed

    private void txtmonto_caja_aperturaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmonto_caja_aperturaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            boton_caja_cierre();
        }
    }//GEN-LAST:event_txtmonto_caja_aperturaKeyPressed

    private void txtmonto_caja_aperturaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmonto_caja_aperturaKeyReleased
        // TODO add your handling code here:
//        evejtf.getDouble_format_nro_entero(txtmonto_caja_abrir);
    }//GEN-LAST:event_txtmonto_caja_aperturaKeyReleased

    private void btncaja_abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncaja_abrirActionPerformed
        // TODO add your handling code here:
        boton_caja_cierre();
    }//GEN-LAST:event_btncaja_abrirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if(evemen.MensajeGeneral_question("DESEAS SALIR DEL SISTEMA","SISTEMA","SALIR","CANCELAR")){
            System.exit(0);
        }
            
    }//GEN-LAST:event_formWindowClosing

    private void txtmonto_caja_aperturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmonto_caja_aperturaKeyTyped
        // TODO add your handling code here:
        evejtf.soloNumero(evt);
    }//GEN-LAST:event_txtmonto_caja_aperturaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDiaAbrir_Caja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDiaAbrir_Caja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDiaAbrir_Caja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDiaAbrir_Caja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDiaAbrir_Caja dialog = new JDiaAbrir_Caja(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncaja_abrir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panel_insert;
    private javax.swing.JPanel panel_insert1;
    private javax.swing.JTextField txtmonto_caja_abrir;
    private javax.swing.JTextField txtmonto_caja_apertura;
    // End of variables declaration//GEN-END:variables
}
